export const Colors = {
  light: {
    primary: "#6750A4",
    onPrimary: "#FFFFFF",
    primaryContainer: "#EADDFF",
    onPrimaryContainer: "#21005E",
    secondary: "#958DA5",
    onSecondaryContainer: "#F4EDFF",
    surface: "#FEF7FF",
    onSurface: "#1C1B1F",
    surfaceVariant: "#E7E0EC",
    onSurfaceVariant: "#49454F",
    outline: "#79747E",
    outlineVariant: "#CAC4D0",
    background: "#FEF7FF",
    onCancel: "#EF5350",
    onError: "#FFFFFF",
    elevation: {
      level0: "transparent",
      level1: "#F7F2FA",
      level2: "#F3EDF7",
    },
  },
  dark: {
    primary: "#673AB7",
    onPrimary: "#381E72",
    primaryContainer: "#7E57C2",
    onPrimaryContainer: "#EADDFF",
    secondary: "#CCC2DC",
    onSecondaryContainer: "#9575CD",
    surface: "#1C1B1F",
    onSurface: "#E6E1E5",
    surfaceVariant: "#49454F",
    onSurfaceVariant: "#FFFFFF",
    outline: "#938F99",
    outlineVariant: "#49454F",
    background: "#1C1B1F",
    onCancel: "#EF5350",
    onError: "#FFFFFF",
    elevation: {
      level0: "transparent",
      level1: "#2D2A31",
      level2: "#36343B",
    },
  },
};
